import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat, Exo_2 } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-montserrat",
});
const exo_2 = Exo_2({
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-exo2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ru"
      className={`${montserrat.variable} ${exo_2.variable} h-full`}
    >
      <body className="font-montserrat h-full">
        <Header />
        <div className="mt-20 h-full">{children}</div>
      </body>
    </html>
  );
}
