version: "2"

services:
  backend:
    image: "dmitrykulakovfrontend/cringeneers-backend:latest"
    build:
      context: ./backend
    container_name: backend
    environment:
      - DB_URL=jdbc:postgresql://91.185.85.237:5432/rlthackdb
      - DB_USERNAME=cringe
      - DB_PASSWORD=supercringe
    ports:
      - 8080:8080

  frontend:
    image: "dmitrykulakovfrontend/cringeneers-frontend:latest"
    ports:
      - 3000:3000
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
